FROM node:24.16.0-bookworm-slim AS base

# ----------------------------
# Stage 1: Install all dependencies
# ----------------------------
FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# ----------------------------
# Stage 2: Build the application
# ----------------------------
FROM deps AS build
WORKDIR /app
COPY . .
RUN node ace build

# ----------------------------
# Stage 3: Production runtime
# ----------------------------
FROM base AS production
WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/build ./
COPY setup.sh ./
RUN chmod +x setup.sh

RUN npm ci --omit=dev

EXPOSE 3333

ENTRYPOINT ["sh" , "/app/setup.sh"]
CMD ["node", "bin/server.js"]