FROM node:24.16.0-alpine3.24 AS base

WORKDIR /app

# ----------------------------
# Stage 1: Install all dependencies
# ----------------------------
FROM base AS deps
COPY package*.json ./
RUN npm ci

# ----------------------------
# Stage 2: Build the application
# ----------------------------
FROM deps AS build
COPY . .
RUN node ace build
# Remove dev dependencies after build to reduce image size
COPY package*.json ./
RUN npm ci --omit=dev
# ----------------------------
# Stage 3: Production runtime
# ----------------------------
FROM dhi.io/node:24-alpine AS production
ENV NODE_ENV=production

COPY --from=build /app/build ./
COPY --from=build /app/node_modules ./node_modules
COPY entrypoint.mjs ./

ENTRYPOINT ["node", "entrypoint.mjs"]
